<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'system' => array($baseDir . '/'),
    'jyggen\\Curl' => array($vendorDir . '/jyggen/curl/lib'),
    'controllers' => array($baseDir . '/app'),
    'Twig_Extensions_' => array($vendorDir . '/slim/extras/Views/Extension'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Slim\\Extras' => array($vendorDir . '/slim/extras'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'RedBean_' => array($vendorDir . '/gabordemooij/redbean'),
);
